== Introduction

OGC https://www.ogc.org/standards/geosparql/[GeoSPARQL] is an open standard that enables storage and exchange of spatial data on the Web, based on the Resource Description Framework (RDF). In 2020 the OGC white paper https://docs.ogc.org/wp/19-078r1/19-078r1.html[Benefits of Representing Spatial Data Using Semantic and Graph Technologies] was published. It explained the benefits of GeoSPARQL and described the ways in which GeoSPARQL version 1.0 could be improved. In the meantime, version 1.1 GeoSPARQL has been published, having many improvements described in the white paper. Currently, version 1.3 is in development. This next version will have an emphasis on improved 3D capabilities.

Although not specifically bound, GeoSPARQL 1.1 is mainly geared towards spatial objects having zero to two dimensions. In other words, things that can be displayed on a flat surface. However, for three-dimensional spatial objects both supply and demand are increasing.

GeoSPARQL 1.3 is expected to have extended capabilities supporting three-dimensional space. Not only would that make GeoSPARQL more useful for 3D geospatial data, it would also help in industries and knowledge domains that are not mainly focused on geospatial data, like Building Information Modelling (BIM) and Computer Graphics (CG). This paper describes which extensions to GeoSPARQL for 3D are possible, which are most desirable, and how they could be achieved.

This paper consists of three main parts. The first section describes current capabilities of GeoSPARQL: in its current state, GeoSPARQL does allow modelling three-dimensional objects, but with relevant limitations. The second section describes requirements for extended 3D capabilities in GeoSPARQL. This is based on a market consultation, which resulted in a collection of use cases for additional 3D capabilities. By analysing those use cases, as well as current developments within and outside the OGC, insight in the most needed extensions to GeoSPARQL can be obtained. Requirements are then weighed against feasibility; some extensions are easier to achieve than others. The third and final section describes the expected benefits for additional 3D capabilities in GeoSPARQL for different domains and different roles.

This paper should be interesting for the following audiences:

* Current and prospective users of GeoSPARQL;
* Current and prospective implementers of GeoSPARQL;
* Members of related OGC working groups.

A deep understanding of the Semantic Web and graph technologies is not required for readers of this white paper, but some interest in those topics is assumed, as well as familiarity with the aformentioned white paper https://docs.ogc.org/wp/19-078r1/19-078r1.html[Benefits of Representing Spatial Data Using Semantic and Graph Technologies]. This paper focuses on specifically on 3D capabilities of GeoSPARQL, not its general benefits.
