== Introduction

OGC https://www.ogc.org/standards/geosparql/[GeoSPARQL] is an open standard that enables storage and exchange of spatial data on the Web, based on the Resource Description Framework (RDF) <<RDF_2014>>. It allows querying geospatial data that is made available in RDF, while explicitly also allowing to make geometric queries (within, distance, etc.). In 2020, the OGC white paper https://docs.ogc.org/wp/19-078r1/19-078r1.html[Benefits of Representing Spatial Data Using Semantic and Graph Technologies] was published. It explained the benefits of GeoSPARQL and described the ways in which GeoSPARQL version 1.0 could be improved. In the meantime, https://docs.ogc.org/is/22-047r1/22-047r1.html[GeoSPARQL version 1.1] has been published, having many improvements described in aforementioned white paper, see also https://www.mdpi.com/2220-9964/11/2/117[this introduction to GeoSPARQL 1.1] <<ijgi11020117>>.

Although not specifically bound, GeoSPARQL 1.1 is mainly geared towards spatial objects having zero to two dimensions. In other words, things that can be displayed on a flat surface. However, for three-dimensional spatial objects, both supply and demand are increasing. There is an increasing need to be able to query geometric relations between objects and geometric properties of elements in three dimensions (e.g. within, intersecting, above, next to).

Two new versions of GeoSPARQL are in development: v1.2 and v1.3. GeoSPARQL 1.2 will be an update of GeoSPARQL 1.1 which enables GeoSPARQL to be published as an ISO standard. Version 1.2 will have no substantive changes with respect to version 1.1. GeoSPARQL 1.3 is expected to have extended capabilities supporting three-dimensional (3D) space. Not only would that make GeoSPARQL more useful for 3D geospatial data, it would also help in industries and knowledge domains that are not mainly focused on geospatial data, like Building Information Modelling (BIM), Civil Infrastructure Engineering, and Computer Graphics (CG). This paper describes which extensions to GeoSPARQL for 3D are possible, which are most desirable, and how they could be achieved.

This paper consists of three main parts. The first section describes current capabilities of GeoSPARQL: in its current state, GeoSPARQL allows modelling three-dimensional objects, but with relevant limitations. The second section describes requirements for extended 3D capabilities in GeoSPARQL. This is based on a market consultation, which resulted in a collection of use cases for additional 3D capabilities. By analysing those use cases, as well as current developments within and outside the OGC, insight in the most needed extensions to GeoSPARQL can be obtained. Requirements are then weighed against feasibility; some extensions are easier to achieve than others. The third and final section describes the expected benefits for additional 3D capabilities in GeoSPARQL for different domains and different roles.

This paper should be interesting for the following audiences:

* Current and prospective users of GeoSPARQL;
* Current and prospective implementers of GeoSPARQL;
* Members of related OGC working groups;
* BIM- and GIS-related developers.

A deep understanding of the Semantic Web and graph technologies is not required for readers of this white paper, but some interest in those technologies is assumed, as well as familiarity with the aformentioned white paper https://docs.ogc.org/wp/19-078r1/19-078r1.html[Benefits of Representing Spatial Data Using Semantic and Graph Technologies]. This paper focuses specifically on 3D capabilities of GeoSPARQL, not on the general benefits of using Semantic Web and graph technologies.
