== Current capabilities

=== GeoSPARQL

GeoSPARQL is the most common geospatial extension of SPARQL. It was accepted as an OGC standard in 2012 and revised as GeoSPARQL 1.1 in 2024.

According to the standard document, "The OGC GeoSPARQL standard supports representing and querying geospatial data on the Semantic Web. GeoSPARQL defines a vocabulary for representing geospatial data in RDF, and it defines an extension to the SPARQL query language for processing geospatial data".

==== Requirements addressed

In order to define which capabilities GeoSPARQL needs to adopt for full 3D compatibility, we first take a look at GeoSPARQL 1.1 current capabilities with regards to 3D.

===== Literals

A first requirement for 3D support is the ability to save 3D data in a knowledge graph.
GeoSPARQL 1.1 defines a variety of String literal formats, which are investigated for the storage of 3D data.

[cols="3,3,3,3"] 
|=== 
|Literal Type | Z-Coordinate Supported | 2.5D | 3D 
|WKT Literal  | Yes | Yes | Yes
|GML Literal  |  |  | 
|KML Literal  |  |  |
|GeoJSON Literal  |  |  |
|DGGS Literal  |  |  | 
|=== 

GeoSPARQL 1.1 also does not restrict the usage of coordinate reference systems with 3D support.
There are currently almost 300 coordinate reference systems in the database epsg.io (https://epsg.io/?q=%20kind%3AGEOG3DCRS) which can be used to describe 3D data encoded in the GeoSPARQL graph literals listed above.

===== Query functions with 3D support
GeoSPARQL 1.1 functions currently do not offer fully-featured 3D support. 
However, there are functions which may take into account the Z coordinate, if they are available.

[cols="3,3,3,3"] 
|=== 
|GeoSPARQL function | Z-Coordinate Supported | 2.5D | 3D 
|geof:is3D  | Yes | Yes | Yes
|geof:minZ  | Yes | Yes | Yes
|geof:maxZ  | Yes | Yes | Yes 
|=== 
These functions check for the presence of Z coordinates or filter out maximum and minimum Z coordinates of the given geometry.

==== Adoption of GeoSPARQL 1.1
