== Requirements for GeoSPARQL 3D

This section provides an overview of feedback received on the current version of the GeoSPARQL standard (version 1.1) regarding 3D usage. 
This feedback helps to identify some of the barriers to use, and to outline requirements that have not been addressed that may encourage greater uptake.

=== Proposed extensions for GeoSPARQL 3D

==== Extension 1: 3D representations

===== GitHub Issue URI

https://github.com/opengeospatial/ogc-geosparql/issues/583

===== Category

Semantic improvement

===== Description

GeoSPARQL should include ways to represent 3D data in a knowledge graph.

3D data should be included in common 3D formats and 3D data should be includable as a text literal and a file representation.

Some common formats which could be considered for inclusion are:

- Polygon File Format (PLY)
- Wavefront OBJ Format (OBJ)
- GLTF Format (GLTF)

==== Extension 2: Relations of 3D geometries

===== GitHub Issue URI

https://github.com/opengeospatial/ogc-geosparql/issues/416

===== Category

Semantic improvement

===== Description

GeoSPARQL should include ways to represent relations between 3D geometries and relations between 3D geometries and geometries of lower dimensions.
The relations should be expressable in property relations and should be queryable using SPARQL extension functions.

==== Extension 3: Appearance of 3D geometries

===== GitHub Issue URI

https://github.com/opengeospatial/ogc-geosparql/issues/592

===== Category

Semantic improvement

===== Description

GeoSPARQL should include ways to represent materials and textures of 3D geometries, so that geometries can be styled accordingly.

