This is still just a dump of resources. To be transformed into actual text.

== CityGML


https://www.mdpi.com/2220-9964/12/9/351
IFC-CityGML Data Integration for 3D Property Valuation

This article describes what became known as Onto CityGML, so far the closest thing to GeoSPARQL3D.


https://www.cambridge.org/core/journals/data-centric-engineering/article/semantic-3d-city-interfacesintelligent-interactions-on-dynamic-geospatial-knowledge-graphs/975E518C41DCDD8BD565012C9E2C8473
Semantic 3D city interfaces—Intelligent interactions on dynamic geospatial knowledge graphs

Knowledge graphs construction for 3D city data. Related the CityGML and Onto CityGML.


https://link.springer.com/article/10.1007/s41064-020-00095-z
CityGML 3.0: New Functions Open Up New Applications

Looks like the Semantic Web is fully considered in CityGML 3.0. Possibly demanding aligments with GeoSPARQL3D. Question: what can GeoSPARQL add that is not yet in CityGML?


https://lup.lub.lu.se/student-papers/search/publication/9169387
Linked geodata: CityGML represented as a virtual knowledge graph

More knowledge graphs constructed from CityGML.


https://www.sciencedirect.com/science/article/pii/S2666546821000574?via%3Dihub
Semantic 3D City Database — An enabler for a dynamic geospatial knowledge graph

Other details and history of Onto CityGML.


== Medicine & Chemistry

https://www.nature.com/articles/s41597-022-01562-5
Standard metadata for 3D microscopy

The 3D Microscopy Metadata Standards (3D-MMS), developed by the BRAIN 3D Microscopy Working Group, help ensure that a 3D microscopy dataset is sufficiently described to support its’ re-use by scientists who did not generate the data. Adoption of 3D-MMS will aid investigators who want to share data, helping them to evaluate and decide which data can be combined. 
https://doryworkspace.org/metadata


https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13083
Ontology-Based Representation and Modelling of Synthetic 3D Content: A State-of-the-Art Review

A range of approaches have been proposed to permit semantic representation and modelling of synthetic 3D content. These approaches differ in the methodologies and technologies used as well as their scope and application domains. This paper provides a review of the current state of the art in representation and modelling of 3D content based on semantic web ontologies, together with a classification, characterization and discussion of the particular approaches.


https://www.inderscienceonline.com/doi/abs/10.1504/IJMSO.2017.087702
A novel ontology for 3D semantics: ontology-based 3D model indexing and content-based video retrieval applied to the medical domain

This paper presents the most comprehensive formally grounded 3D ontology to date that maps the entire XSD-based vocabulary of the industry standard X3D (ISO/IEC 19775-19777) to OWL 2, complemented by fundamental concepts and roles of the 3D modelling industry not covered by X3D.

== To consider

https://link.springer.com/article/10.1007/s10845-023-02246-6
Ontology of 3D virtual modeling in digital twin: a review, analysis and thinking

To help novice engineers understand and scheme 3D virtual modeling in digital twin for future research and applications, this paper reviews 106 digital twin 3D modeling cases with their characteristics, including deployment targets, purposes & roles, collaborative models, data flows, the autonomy of 3D modeling, fidelity, twinning rates, enabling technologies, and enabling tools. 


STereoLithography (STL)
http://www.3dsystems.com/quickparts/learning-center/what-is-stl-file

STL files describe only the surface geometry of a three-dimensional object without any representation of color, texture or other common CAD model attributes. The STL format specifies both ASCII and binary representations.


Open standard for particle-mesh data (openPMD)
https://github.com/openPMD/openPMD-standard

The openPMD standard, short for open standard for particle-mesh data files is not a file format per se. It is guidance for meta data and naming schemes. openPMD provides naming and attribute conventions that allow to exchange particle and mesh based data from scientific simulations and experiments. The primary goal is to define a minimal set/kernel of meta information that allows to share and exchange data to achieve portability between various applications and differing algorithms, a unified open-access description for scientific data (publishing and archiving), and a unified description for post-processing, visualization and analysis. If output from programs, devices (such as cameras), simulations or post-processed data-sets contain a minimal set of meta information as provided by openPMD, you can exchange data between those with minimal effort and you use the same tools for visualization.


CARARE Metadata Schema
https://pro.carare.eu/en/introduction-carare-aggregation-services/carare-metadata-schema/


The CARARE metadata schema is a harvesting schema intended for delivering metadata about an organisation’s online collections, heritage assets and their digital resources. The strength of the schema lies with its ability to support the full range of descriptive information about monuments, building, landscape areas and their representations. The CARARE metadata schema builds on existing standards and best practice from a number of different countries in Europe and the rest of the world.
