= GeoSPARQL 3D White Paper

This repository contains the source code for the _GeoSPARQL 3D White Paper_ being prepared by members of the https://www.ogc.org/domain-working-groups/[Geosemantics Domain Working Group (DWG)], the https://www.ogc.org/standards-working-groups/[GeoSPARQL Standard Working Group (SWG)] and colleagues from the https://www.w3.org/2021/sdw/[OGC/W3C Spatial Data on the Web Working Group].

The purpose of the White Paper is to establish the direction and scope of http://www.opengis.net/doc/IS/geosparql/1.1[GeoSPARQL]'s handling of 3D - ontological elements, coordinate representations, topological functions and other functions.

This White Paper appears online in developing form at:

*https://opengeospatial.github.io/geosparql3dwhitepaper/*

== Contact

To be involved with this White Paper, please contact:

* White Paper lead:
** Rolf Jonker - r.jonker@geonovum.nl
* GeoSemantics DWG Chairs:
** Joseph Abhayaratna - joseph.abhayaratna@geoscape.com.au
** Linda van den Brink - l.vandenbrink@geonovum.nl

Or please place issues in this repository's Issue Tracker:

https://github.com/opengeospatial/geosparql3dwhitepaper/issues

== Technical details

This White Paper is built using the https://www.metanorma.org/[Metanorma] tool using the https://github.com/metanorma/mn-templates-ogc/tree/master/white-paper[standard OGC White Paper template].

=== Content

This GitHub repository contains the content for an OGC White Paper.

* `document.adoc` - the main White Paper document with references to all sections
* remaining ``adoc``s - each section of the White Paper document is in a separate document
** follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)

=== Building

Run `make`.
