# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push: 
      branches: 
          - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Metanorma Whitepaper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/cache@v3
      with:
        path: ~/.fontist
        key: fontist-ubuntu-latest
        restore-keys: fontist-ubuntu-latest

    - uses: actions-mn/setup@main

    - name: Run Metanorma 🔧
      run: |
         pip install bibtexparser
         python scripts/processbibtex.py
         metanorma site generate --agree-to-terms -o site

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         clean: false
         FOLDER: site/
